const COPY = {
  sw: {
    customization: { eyebrow: "Mkusanyiko wako", title: "Unda avatar yako", subtitle: "Kila kitu unachokikubali hubakuwa alama yako. Salio: {gems} 💎", currentLook: "Mwonekano wako wa sasa", exclusive: "Kipekee", select: "Chagua", active: "Inatumika", unlock: "Fungua · {amount} 💎", completeAchievement: "Kamilisha mafanikio", achievementRequired: "Kamilisha mafanikio yaliyounganishwa ili kufungua kitu hiki.", notEnoughGems: "Unahitaji gems {amount} zaidi.", unlockedToast: "Kimefunguliwa na kuchaguliwa", selectedToast: "Uteuzi mpya umetumika", error: "Badilisha la personalization imeshindikana.", tabs: { avatar: "Vijina", hat: "Kofia", glasses: "Miwani", background: "Mandhari" }, rarity: { common: "Kawaida", rare: "Adimu", epic: "Epiki", legendary: "Legendarisi" } },
    space: { title: "Nafasi yangu", guest: "Wageni", identity: "Utambulisho wa kuonekana", yourAvatar: "Avatar yako, alama yako", customize: "Badilisha", customizeHint: "Unda avatar yako na uweke gems ulizopata kwenye mkusanyiko wako.", noFocus: "Hakuna lugha ya kipaumbele", level: "Kiwango", streak: "Mfululizo", gems: "Gems", collections: "Mikusanyiko", collectionHint: "Vijina 50 · kofia 15 · miwani 10 · mandhari 10", achievements: "Alama na mafanikio", achievementHint: "Kila utafanikio hujimarisha mkusanyiko wako.", noAchievements: "Kamilisha mafanikio ili kuonyesha alama yako ya kwanza." },
  },
  ln: {
    customization: { eyebrow: "Ta collection", title: "Sala avatar na yo", subtitle: "Biso nyonso ekoko成为 bo motó na yo. Montant: {gems} 💎", currentLook: "Look na yo ya sika", exclusive: "Exclusif", select: "Pona", active: "Motó", unlock: "Fungola · {amount} 💎", completeAchievement: "Finish achievement", achievementRequired: "Finish achievement esuili moko elandani na yo epota kofungola kino.", notEnoughGems: "Bozali gems {amount} kolekisa.", unlockedToast: "Kofungoli mpe poni", selectedToast: "Selection mokinsangi ete lisusu", error: "Personnalisation ekotaki.", tabs: { avatar: "Avatars", hat: "Bokas", glasses: "Miso ya meso", background: "Mbandɔ" }, rarity: { common: "Kawaida", rare: "Kokoka", epic: "Epiki", legendary: "Legendarisi" } },
    space: { title: "Espika na ngai", guest: "Session visiteur", identity: "Identité ya.visible", yourAvatar: "Avatar na yo, emblème na yo", customize: "Personnalise", customizeHint: "Sala avatar na yo mpe kosala gems na yo collection.", noFocus: "Lokota te ya.focus", level: "Nivo", streak: "Mikolo", gems: "Gems", collections: "Mikusanyiko", collectionHint: "Avatars 50 · bokas 15 · miso 10 · mbandɔ 10", achievements: "Badges mpe achievements", achievementHint: "Nyonso differance ikabolisa collection.", noAchievements: "Finish achievement moko mwa komonana badge ya kwanza." },
  },
  ha: {
    customization: { eyebrow: "Tarin ka", title: "Ƙirƙiri hotonka", subtitle: "Kowane abu da ka karɓi zai kasu alamarhanka. Ma'auni: {gems} 💎", currentLook: "Yanayin hoto da yanzu", exclusive: "Musammamman", select: "Zaɓi", active: "Aiki", unlock: "Buɗe · {amount} 💎", completeAchievement: "Kammala nasara", achievementRequired: "Kammala nasara da ke da alaka don buɗe wannan abu.", notEnoughGems: "Kana buƙatar{data} gems {amount} ƙari.", unlockedToast: "An buɗe kuma an zaɓi", selectedToast: "An yi amfani da sabo zaɓi", error: "Tsarin personalization ya gaza.", tabs: { avatar: "Hotuna", hat: "Hatsi", glasses: "Manya", background: "Bayansa" }, rarity: { common: "Na yau", rare: "Mai wuya", epic: "Babba", legendary: "Labari" } },
    space: { title: "Sararinsa", guest: "Zaman访客", identity: "Sanewa bayanai", yourAvatar: "Hotonka, zamaranta", customize: "Tsara", customizeHint: "Ƙirƙiri hoto kuma sanya gems ɗa ka samu a cikin gado.", noFocus: "Babu harshen mai mafi girma", level: "Mataki", streak: "Kwana", gems: "Gems", collections: "Tattara", collectionHint: "Hotuna 50 · hatsi 15 · manya 10 · bayansa 10", achievements: "Alama da nasara", achievementHint: "Kowane alama tana karɓar da tattararka.", noAchievements: "Kammala nasara don nuna alamar farko." },
  },
  yo: {
    customization: { eyebrow: "Àkójọ rẹ", title: "Kọ àwòrán rẹ", subtitle: "Ohun kọ̀ọ̀kan tí o bẹ̀wọ́ di àmì ìdánwò rẹ. Ìyókù: {gems} 💎", currentLook: "Ìríṣe rẹ lọ́wọ́", exclusive: "Àti tì í ní", select: "Yan", active: "Ṣiṣẹ́", unlock: "Ṣí · {amount} 💎", completeAchievement: "Parí èṣeyọ̀", achievementRequired: "Parí èṣeyọ̀ tí ó bá pọ̀ só ẹyìn ṣí ohun náà.", notEnoughGems: "O nílò{data} gems mìíràn.", unlockedToast: "Ṣí tí o sì yan", selectedToast: "Aṣàwákiri tuntun ti wọlé", error: "Àtúnṣe àwòrán kò sọ́rọ̀.", tabs: { avatar: "Àwòrán", hat: "Adé", glasses: "Àwọn ọjọ́", background: "Ìtàn" }, rarity: { common: "Kọ́wà", rare: "Ẹ̀ṣú", epic: "Títán", legendary: "Àṣà" } },
    space: { title: "Ààyè mi", guest: "Àjẹ́ ìlù", identity: "Ìdánilójú", yourAvatar: "Àwòrán rẹ, àmì rẹ", customize: "Ṣàtúnṣe", customizeHint: "Kọ àwòrán rẹ kí o sì tún gẹ́ ọja rẹ sí àkójọ rẹ.", noFocus: "Kò sí èdè tí a fókù", level: "Ìpèlẹ", streak: "Ọjọ̀", gems: "Gems", collections: "Àkójọ", collectionHint: "Àwòrán 50 ·.adé 15 · ọjọ́ 10 · ìtàn 10", achievements: "Àmì àti èṣeyọ̀", achievementHint: "Èyí kọ̀ọ̀kan dì múlẹ́ àkójọ rẹ.", noAchievements: "Parí èṣeyọ̀ kan láti fi àmì tuntun hàn." },
  },
  zu: {
    customization: { eyebrow: "Iqoqo lakho", title: "Ida i-avatar yakho", subtitle: "Into ngayithola iyiphupha lakho. Ibhalansi: {gems} 💎", currentLook: "Ukubuka kwakho manje", exclusive: "Okukhethekile", select: "Khetha", active: "Kusebenza", unlock: "Vula · {amount} 💎", completeAchievement: "Qeda impumelelo", achievementRequired: "Qeda impumelelo ehambisana nento ukuze uvule kanye.", notEnoughGems: "Udine amagems {amount} eyengeziwe.", unlockedToast: "Kuvulwe futhi kukhethiwe", selectedToast: "Ukukhetha okutsha kusetshenzisiwe", error: "Ukwenza i-avatar akuphumele.", tabs: { avatar: "Ava-avatar", hat: "Ikhasi", glasses: "Izibuko", background: "Umsemu" }, rarity: { common: "Okujwayelekile", rare: "Okuyingqopho", epic: "Okukhulu", legendary: "Umshumane" } },
    space: { title: "Inda yami", guest: "Ukusingeni", identity: "Ukubuka kwami", yourAvatar: "I-avatar yakho, uphawu lwakho", customize: "Lungisa", customizeHint: "Dala i-avatar yakho bese uyiphinda emagems engathola kuqoqobeka.", noFocus: "Awukho ulimi olugxanile", level: "Izinga", streak: "Izinsuku", gems: "Amagems", collections: "Amaqoqobeka", collectionHint: "Ava-avatar 50 · amakhasi 15 · izibuko 10 · imisemu 10", achievements: "Amabandela neziphumelelo", achievementHint: "Isiqondiso ngayinye sithuthukisa iqoqobeka lakho.", noAchievements: "Qeda impumelelo ukuze ubone ibandela lokuqala." },
  },
  wo: {
    customization: { eyebrow: "Sa boroom", title: "Sos raxay bi", subtitle: "Lii mbir doni nga dugg, di dalal bu bees. Xaalis: {gems} 💎", currentLook: "Sa mbir bu lay bu bi", exclusive: "Bu bees", select: "Tann", active: "Dio", unlock: "Ubbi · {amount} 💎", completeAchievement: "Fini achievement bi", achievementRequired: "Fini achievement bi mbir nga fëgg nga ubbi kats bi.", notEnoughGems: "Doyul gems {amount} yeneen.", unlockedToast: "Bu ubbi mooy di tann", selectedToast: "Tann buu ngi yóbbu di kópp", error: "Sos raxay bi amba nga jur.", tabs: { avatar: "Raxay", hat: "Kop", glasses: "Lunettes", background: "Li mbir" }, rarity: { common: "Taxawaay", rare: "Sëriiña", epic: "Epik", legendary: "Legendarisi" } },
    space: { title: "Kër gi", guest: "Waas bu semm", identity: "Li lay bu bees", yourAvatar: "Raxay bi, marra du raxay", customize: "Sos", customizeHint: "Sos raxay bi, gënci gems yi mbaremb ya bitey collection.", noFocus: "Amul làkk bu ndal", level: "Tolluwaay", streak: "Bisse", gems: "Gems", collections: "Tig collection", collectionHint: "Raxay 50 · kop 15 · lunettes 10 · li mbir 10", achievements: "Badge ak achievement", achievementHint: "Bii tuntum bu tog strengthen collection bi.", noAchievements: "Fini achievement waxtu benn non pouray badgeICl." },
  },
} as const;

export function getMod6Copy(lang: string): unknown | undefined {
  return COPY[lang as keyof typeof COPY];
}
