import { internalMutation, query } from "./_generated/server";
import { v, type Infer } from "convex/values";
import { contactHeaders, envReady, envValue, hasEnv } from "./ovEnv";
import { specKeys } from "./connectors";

/* ═══════════════════════════════════════════════════════════════════════
   MOOVY — REGISTRE DES CONNECTEURS

   Chaque source externe est décrite ici, et chaque connecteur réellement
   branché a son implémentation dans `connectors/`.

   ⚠️ Une source de MÉTADONNÉES n'est jamais une source de streaming.
      Savoir qu'un film existe ne signifie pas qu'on peut le diffuser.
      `provides` / `allowsRedistribution` / `supportsEmbed` décrivent ce que
      la source autorise, et le Rights Engine tranche ensuite contenu par
      contenu.

   `implemented` est un garde-fou d'honnêteté : il est vérifié au démarrage
   contre `connectors/index.ts`. Une source déclarée mais non branchée est
   affichée « registre » — jamais « active ».
   ═══════════════════════════════════════════════════════════════════════ */

export const connectorValidator = v.object({
  key: v.string(),
  name: v.string(),
  /** metadata : informations seulement. content : œuvres sous licence
   *  exploitable. index : catalogue/agrégateur. dataset : import massif. */
  kind: v.union(v.literal("metadata"), v.literal("content"), v.literal("index"), v.literal("dataset")),
  category: v.union(
    v.literal("film"),
    v.literal("series"),
    v.literal("video"),
    v.literal("music"),
    v.literal("podcast"),
    v.literal("audio"),
    v.literal("book"),
    v.literal("article"),
    v.literal("image"),
    v.literal("social"),
    v.literal("multi"),
  ),
  homepage: v.string(),
  docsUrl: v.optional(v.string()),
  license: v.string(),
  /** Variables d'environnement à renseigner dans l'onglet Keys/API keys. */
  requiresEnv: v.array(v.string()),
  /** Participe à la recherche par mots-clés. */
  searchEnabled: v.boolean(),
  /** Peut alimenter un rayon sans requête (nouveautés / tendances). */
  discoverEnabled: v.boolean(),
  /** Fournit-il un lecteur officiel intégrable (iframe / oEmbed) ? */
  supportsEmbed: v.boolean(),
  /** Fournit-il un extrait promotionnel officiel jouable ? */
  supportsPreview: v.boolean(),
  /** Autorise-t-il la redistribution des œuvres trouvées ? */
  allowsRedistribution: v.boolean(),
  /** Peut-il alimenter le moteur de transcription / traduction ? */
  transcriptionSource: v.boolean(),
  requiresKey: v.boolean(),
  /** Connecteur réellement implémenté dans `connectors/`. */
  implemented: v.boolean(),
  notes: v.string(),
});

export type Connector = Infer<typeof connectorValidator>;

export const CONNECTORS: Connector[] = [
  /* ── Contenus réellement exploitables (aucune clé requise) ────────── */
  {
    key: "internet_archive",
    name: "Internet Archive",
    kind: "content",
    category: "multi",
    homepage: "https://archive.org",
    docsUrl: "https://archive.org/developers/",
    license: "Domaine public + licences Creative Commons (varie par item)",
    requiresEnv: [],
    searchEnabled: true,
    discoverEnabled: true,
    supportsEmbed: true,
    supportsPreview: false,
    allowsRedistribution: true,
    transcriptionSource: true,
    requiresKey: false,
    implemented: true,
    notes:
      "Films, audio, textes. La licence est lue par item (licenseurl) : sans licence explicite, le contenu reste UNKNOWN et n'est jamais streamé. Alimente aussi les rayons Films/Audio par nouveauté et popularité.",
  },
  {
    key: "prelinger",
    name: "Prelinger Archives",
    kind: "content",
    category: "film",
    homepage: "https://archive.org/details/prelinger",
    docsUrl: "https://archive.org/developers/",
    license: "Domaine public",
    requiresEnv: [],
    searchEnabled: true,
    discoverEnabled: true,
    supportsEmbed: true,
    supportsPreview: false,
    allowsRedistribution: true,
    transcriptionSource: true,
    requiresKey: false,
    implemented: true,
    notes: "Films pédagogiques et publicitaires du domaine public (sous-ensemble d'Internet Archive).",
  },
  {
    key: "gutendex",
    name: "Project Gutenberg (Gutendex)",
    kind: "content",
    category: "book",
    homepage: "https://www.gutenberg.org",
    docsUrl: "https://gutendex.com/",
    license: "Domaine public",
    requiresEnv: [],
    searchEnabled: true,
    discoverEnabled: true,
    supportsEmbed: false,
    supportsPreview: false,
    allowsRedistribution: true,
    transcriptionSource: true,
    requiresKey: false,
    implemented: true,
    notes:
      "Textes intégraux du domaine public : lecture, traduction et analyse autorisées. Réactivé — l'API redirige (301) puis répond normalement, le client HTTP suit la redirection et réessaie.",
  },
  {
    key: "librivox",
    name: "LibriVox (via Internet Archive)",
    kind: "content",
    category: "audio",
    homepage: "https://librivox.org",
    docsUrl: "https://archive.org/developers/",
    license: "Domaine public (enregistrements bénévoles)",
    requiresEnv: [],
    searchEnabled: true,
    discoverEnabled: true,
    supportsEmbed: true,
    supportsPreview: false,
    allowsRedistribution: true,
    transcriptionSource: true,
    requiresKey: false,
    implemented: true,
    notes: "Livres audio du domaine public : lecture intégrée, transcription et traduction autorisées.",
  },
  {
    key: "open_library",
    name: "Open Library",
    kind: "metadata",
    category: "book",
    homepage: "https://openlibrary.org",
    docsUrl: "https://openlibrary.org/developers/api",
    license: "Métadonnées ouvertes ; les œuvres restent sous leurs droits",
    requiresEnv: [],
    searchEnabled: true,
    discoverEnabled: true,
    supportsEmbed: false,
    supportsPreview: false,
    allowsRedistribution: false,
    transcriptionSource: false,
    requiresKey: false,
    implemented: true,
    notes:
      "Catalogue mondial. Quand l'API annonce « ebook_access: public », le connecteur va chercher le texte réel auprès d'Internet Archive et vérifie sa licence : la lecture reste alors dans MOOVY. Sinon la fiche reste informative.",
  },
  {
    key: "itunes",
    name: "Apple iTunes / Apple Music",
    kind: "index",
    category: "multi",
    homepage: "https://performance-partners.apple.com/search-api",
    docsUrl: "https://performance-partners.apple.com/search-api",
    license: "Extraits promotionnels officiels (30 à 90 s)",
    requiresEnv: [],
    searchEnabled: true,
    discoverEnabled: true,
    supportsEmbed: true,
    supportsPreview: true,
    allowsRedistribution: false,
    transcriptionSource: false,
    requiresKey: false,
    implemented: true,
    notes:
      "Recherche et classements publics (morceaux les plus écoutés, podcasts les plus suivis par pays). Seuls les extraits promotionnels fournis par Apple sont jouables ; la fiche officielle reste la seule source complète.",
  },
  {
    key: "deezer",
    name: "Deezer",
    kind: "index",
    category: "music",
    homepage: "https://www.deezer.com",
    docsUrl: "https://developers.deezer.com/api",
    license: "Extraits officiels de 30 s publiés pour l'écoute publique",
    requiresEnv: [],
    searchEnabled: true,
    discoverEnabled: true,
    supportsEmbed: false,
    supportsPreview: true,
    allowsRedistribution: false,
    transcriptionSource: false,
    requiresKey: false,
    implemented: true,
    notes:
      "Catalogue musical réel sans clé : recherche et classement global. Seul l'extrait officiel de 30 s fourni par Deezer est jouable dans le lecteur intégré ; la fiche officielle reste la source complète.",
  },
  {
    key: "google_books",
    name: "Google Books",
    kind: "index",
    category: "book",
    homepage: "https://books.google.com",
    docsUrl: "https://developers.google.com/books",
    license: "Aperçus officiels fournis par les éditeurs via Google Books",
    requiresEnv: [],
    searchEnabled: true,
    discoverEnabled: true,
    supportsEmbed: true,
    supportsPreview: false,
    allowsRedistribution: false,
    transcriptionSource: false,
    requiresKey: false,
    implemented: true,
    notes:
      "Catalogue éditorial récent sans clé (tri natif par nouveauté). Quand l'éditeur autorise l'aperçu, le lecteur web officiel est intégré dans l'application ; sinon la fiche reste informative.",
  },
  {
    key: "jamendo",
    name: "Jamendo Music",
    kind: "content",
    category: "music",
    homepage: "https://www.jamendo.com",
    docsUrl: "https://developer.jamendo.com",
    license: "Musique sous licence Creative Commons, fichiers intégraux publics",
    requiresEnv: [],
    searchEnabled: true,
    discoverEnabled: true,
    supportsEmbed: false,
    supportsPreview: false,
    allowsRedistribution: true,
    transcriptionSource: true,
    requiresKey: false,
    implemented: true,
    notes: "Catalogue musical libre : lecture intégrale en streaming dans MOOVY, transcription et traduction autorisées.",
  },
  {
    key: "audius",
    name: "Audius",
    kind: "content",
    category: "music",
    homepage: "https://audius.co",
    docsUrl: "https://docs.audius.org",
    license: "Contenu publié en écoute publique par les artistes",
    requiresEnv: [],
    searchEnabled: true,
    discoverEnabled: true,
    supportsEmbed: false,
    supportsPreview: false,
    allowsRedistribution: false,
    transcriptionSource: true,
    requiresKey: false,
    implemented: true,
    notes: "Réseau musical ouvert : flux intégral publié par les artistes, lu en streaming dans MOOVY sans copie ni hébergement.",
  },
  {
    key: "dailymotion",
    name: "Dailymotion",
    kind: "content",
    category: "video",
    homepage: "https://www.dailymotion.com",
    docsUrl: "https://developers.dailymotion.com/api/",
    license: "Lecteur officiel intégré ; contenu publié par les créateurs pour la diffusion publique",
    requiresEnv: [],
    searchEnabled: true,
    discoverEnabled: true,
    supportsEmbed: true,
    supportsPreview: false,
    allowsRedistribution: false,
    transcriptionSource: true,
    requiresKey: false,
    implemented: true,
    notes: "API publique sans clé : recherche et nouveautés réelles (tri natif par date), lecture via le lecteur officiel intégré.",
  },
  {
    key: "podcasts",
    name: "Podcasts — index + flux RSS éditeurs",
    kind: "content",
    category: "podcast",
    homepage: "https://podcasts.apple.com",
    docsUrl: "https://performance-partners.apple.com/search-api",
    license: "Flux RSS publics publiés par les éditeurs",
    requiresEnv: [],
    searchEnabled: true,
    discoverEnabled: true,
    supportsEmbed: false,
    supportsPreview: false,
    allowsRedistribution: false,
    transcriptionSource: false,
    requiresKey: false,
    implemented: true,
    notes:
      "L'index sert à trouver l'émission, le flux RSS de l'éditeur fournit les épisodes. On lit l'enclosure officielle en streaming depuis sa source (aucune copie, aucun hébergement). La transcription reste bloquée tant que l'éditeur ne l'a pas autorisée.",
  },
  {
    key: "radio",
    name: "Radio (radio-browser)",
    kind: "content",
    category: "audio",
    homepage: "https://www.radio-browser.info",
    docsUrl: "https://api.radio-browser.info/",
    license: "Flux publics diffusés par les stations",
    requiresEnv: [],
    searchEnabled: true,
    discoverEnabled: true,
    supportsEmbed: false,
    supportsPreview: false,
    allowsRedistribution: false,
    transcriptionSource: false,
    requiresKey: false,
    implemented: true,
    notes:
      "Annuaire ouvert de webradios, filtrable par pays et par langue. Flux lus en streaming ; les flux HLS (.m3u8), non lisibles nativement, sont écartés plutôt que proposés en erreur.",
  },
  {
    key: "wikimedia_commons",
    name: "Wikimedia Commons",
    kind: "content",
    category: "multi",
    homepage: "https://commons.wikimedia.org",
    docsUrl: "https://commons.wikimedia.org/wiki/Commons:API",
    license: "Creative Commons / domaine public (varie par fichier)",
    requiresEnv: [],
    searchEnabled: true,
    discoverEnabled: false,
    supportsEmbed: false,
    supportsPreview: false,
    allowsRedistribution: true,
    transcriptionSource: true,
    requiresKey: false,
    implemented: true,
    notes: "Images, vidéos et sons libres. La licence de chaque fichier est lue dans extmetadata avant toute lecture.",
  },
  {
    key: "wikipedia",
    name: "Wikipédia",
    kind: "content",
    category: "article",
    homepage: "https://fr.wikipedia.org",
    docsUrl: "https://www.mediawiki.org/wiki/API:Main_page",
    license: "CC BY-SA 4.0 — attribution et partage à l'identique",
    requiresEnv: [],
    searchEnabled: true,
    discoverEnabled: true,
    supportsEmbed: false,
    supportsPreview: false,
    allowsRedistribution: true,
    transcriptionSource: true,
    requiresKey: false,
    implemented: true,
    notes:
      "Articles encyclopédiques réellement lisibles et traduisibles dans l'app (attribution et partage à l'identique obligatoires). Alimente le rayon Articles.",
  },
  {
    key: "wikinews",
    name: "Wikinews",
    kind: "content",
    category: "article",
    homepage: "https://fr.wikinews.org",
    docsUrl: "https://www.mediawiki.org/wiki/API:Main_page",
    license: "CC BY 2.5 — attribution",
    requiresEnv: [],
    searchEnabled: true,
    discoverEnabled: true,
    supportsEmbed: false,
    supportsPreview: false,
    allowsRedistribution: true,
    transcriptionSource: true,
    requiresKey: false,
    implemented: true,
    notes:
      "Articles d'actualité sous licence libre, lisibles et traduisibles. La communauté a annoncé l'arrêt des publications en 2026 : le fonds reste consultable et daté honnêtement.",
  },
  {
    key: "tvmaze",
    name: "TVmaze",
    kind: "metadata",
    category: "series",
    homepage: "https://www.tvmaze.com",
    docsUrl: "https://www.tvmaze.com/api",
    license: "Métadonnées ouvertes (attribution TVmaze)",
    requiresEnv: [],
    searchEnabled: true,
    discoverEnabled: true,
    supportsEmbed: false,
    supportsPreview: false,
    allowsRedistribution: false,
    transcriptionSource: false,
    requiresKey: false,
    implemented: true,
    notes:
      "Fiches de séries et diffusion du jour : le rayon Séries affiche du contenu réellement frais. Aucune diffusion : la fiche renvoie vers la plateforme légale.",
  },
  {
    key: "musicbrainz",
    name: "MusicBrainz",
    kind: "metadata",
    category: "music",
    homepage: "https://musicbrainz.org",
    docsUrl: "https://musicbrainz.org/doc/MusicBrainz_API",
    license: "Métadonnées CC0 ; les enregistrements restent protégés",
    requiresEnv: [],
    searchEnabled: true,
    discoverEnabled: false,
    supportsEmbed: false,
    supportsPreview: false,
    allowsRedistribution: false,
    transcriptionSource: false,
    requiresKey: false,
    implemented: true,
    notes: "Référentiel musical ouvert : enrichit les fiches (album, pays, année) sans fournir de fichier.",
  },
  {
    key: "rss",
    name: "Flux RSS / Atom d'un créateur",
    kind: "content",
    category: "multi",
    homepage: "https://www.rssboard.org/rss-specification",
    license: "Selon le flux : publié par son éditeur",
    requiresEnv: [],
    searchEnabled: false,
    discoverEnabled: false,
    supportsEmbed: false,
    supportsPreview: false,
    allowsRedistribution: false,
    transcriptionSource: false,
    requiresKey: false,
    implemented: true,
    notes:
      "Permet d'ajouter l'URL d'un flux (podcast, blog, créateur indépendant). Les épisodes publiés en enclosure sont écoutables en streaming ; le reste donne une fiche avec lien vers la source.",
  },

  /* ── Vidéo moderne : clé officielle gratuite OU découverte publique ── */
  {
    key: "youtube",
    name: "YouTube",
    kind: "index",
    category: "video",
    homepage: "https://developers.google.com/youtube/v3",
    docsUrl: "https://developers.google.com/youtube/v3/docs",
    license: "Lecteur intégré officiel ; contenu © de ses auteurs",
    requiresEnv: [],
    searchEnabled: true,
    discoverEnabled: true,
    supportsEmbed: true,
    supportsPreview: false,
    allowsRedistribution: false,
    transcriptionSource: false,
    requiresKey: false,
    implemented: true,
    notes:
      "Deux portes d'entrée : API officielle si la clé gratuite YOUTUBE_API_KEY est fournie (classements, durées, vues), sinon découverte via portails publics (Piped/Invidious) — la lecture reste TOUJOURS le lecteur intégré officiel (youtube-nocookie), sans téléchargement ni contournement. La clé améliore les métadonnées et les classements, elle n'est plus obligatoire.",
  },

  /* ── Connecteurs prêts mais en attente de clé API ─────────────────── */
  {
    key: "tmdb",
    name: "TMDB",
    kind: "metadata",
    category: "film",
    homepage: "https://www.themoviedb.org",
    docsUrl: "https://developer.themoviedb.org/docs",
    license: "Métadonnées sous conditions d'attribution TMDB",
    requiresEnv: ["TMDB_API_KEY"],
    searchEnabled: true,
    discoverEnabled: true,
    supportsEmbed: false,
    supportsPreview: false,
    allowsRedistribution: false,
    transcriptionSource: false,
    requiresKey: true,
    implemented: false,
    notes: "Affiches, synopsis, distribution, saisons. Métadonnées uniquement : jamais une source de diffusion.",
  },
  {
    key: "omdb",
    name: "OMDb",
    kind: "metadata",
    category: "film",
    homepage: "https://www.omdbapi.com",
    docsUrl: "https://www.omdbapi.com/",
    license: "Métadonnées IMDb sous licence OMDb",
    requiresEnv: ["OMDB_API_KEY"],
    searchEnabled: true,
    discoverEnabled: false,
    supportsEmbed: false,
    supportsPreview: false,
    allowsRedistribution: false,
    transcriptionSource: false,
    requiresKey: true,
    implemented: false,
    notes: "Complément de notes et de détails techniques.",
  },
  {
    key: "watchmode",
    name: "Watchmode",
    kind: "index",
    category: "film",
    homepage: "https://api.watchmode.com",
    docsUrl: "https://api.watchmode.com/docs/",
    license: "Index de disponibilité légale par plateforme",
    requiresEnv: ["WATCHMODE_API_KEY"],
    searchEnabled: true,
    discoverEnabled: false,
    supportsEmbed: false,
    supportsPreview: false,
    allowsRedistribution: false,
    transcriptionSource: false,
    requiresKey: true,
    implemented: false,
    notes: "« Où puis-je regarder légalement ? » — alimente les liens vers les plateformes officielles.",
  },
  {
    key: "europeana",
    name: "Europeana",
    kind: "content",
    category: "multi",
    homepage: "https://www.europeana.eu",
    docsUrl: "https://pro.europeana.eu/page/apis",
    license: "Domaine public + CC (varie par item)",
    requiresEnv: ["EUROPEANA_API_KEY"],
    searchEnabled: true,
    discoverEnabled: false,
    supportsEmbed: true,
    supportsPreview: false,
    allowsRedistribution: true,
    transcriptionSource: true,
    requiresKey: true,
    implemented: false,
    notes: "Patrimoine culturel européen (clé gratuite sur demande).",
  },
  {
    key: "openverse",
    name: "Openverse",
    kind: "content",
    category: "image",
    homepage: "https://openverse.org",
    docsUrl: "https://api.openverse.org/v1/",
    license: "Creative Commons uniquement",
    requiresEnv: ["OPENVERSE_CLIENT_ID", "OPENVERSE_CLIENT_SECRET"],
    searchEnabled: true,
    discoverEnabled: true,
    supportsEmbed: false,
    supportsPreview: false,
    allowsRedistribution: true,
    transcriptionSource: false,
    requiresKey: true,
    implemented: false,
    notes: "Banque d'images et d'audios sous licence CC, attribution fournie par l'API.",
  },

  /* ── Déclarés, volontairement non branchés ────────────────────────── */
  {
    key: "trakt",
    name: "Trakt",
    kind: "metadata",
    category: "series",
    homepage: "https://trakt.tv",
    docsUrl: "https://trakt.docs.apiary.io/",
    license: "Métadonnées communautaires",
    requiresEnv: ["TRAKT_CLIENT_ID"],
    searchEnabled: false,
    discoverEnabled: false,
    supportsEmbed: false,
    supportsPreview: false,
    allowsRedistribution: false,
    transcriptionSource: false,
    requiresKey: true,
    implemented: false,
    notes: "Tendances et listes communautaires.",
  },
  {
    key: "justwatch",
    name: "JustWatch",
    kind: "index",
    category: "film",
    homepage: "https://www.justwatch.com",
    docsUrl: "https://apis.justwatch.com",
    license: "API non publique — usage à valider contractuellement",
    requiresEnv: [],
    searchEnabled: false,
    discoverEnabled: false,
    supportsEmbed: false,
    supportsPreview: false,
    allowsRedistribution: false,
    transcriptionSource: false,
    requiresKey: false,
    implemented: false,
    notes: "Désactivé volontairement : l'endpoint n'est pas documenté publiquement. À remplacer par Watchmode.",
  },
  {
    key: "imdb_datasets",
    name: "IMDb datasets",
    kind: "dataset",
    category: "film",
    homepage: "https://datasets.imdbws.com",
    docsUrl: "https://developer.imdb.com/non-commercial-datasets/",
    license: "Datasets non commerciaux",
    requiresEnv: [],
    searchEnabled: false,
    discoverEnabled: false,
    supportsEmbed: false,
    supportsPreview: false,
    allowsRedistribution: false,
    transcriptionSource: false,
    requiresKey: false,
    implemented: false,
    notes: "Import local massif (dizaines de Go) — prévu pour un déploiement auto-hébergé, pas pour le runtime Convex.",
  },
  {
    key: "gallica",
    name: "Gallica (BnF)",
    kind: "content",
    category: "book",
    homepage: "https://gallica.bnf.fr",
    docsUrl: "https://api.bnf.fr/",
    license: "Domaine public majoritaire",
    requiresEnv: [],
    searchEnabled: false,
    discoverEnabled: false,
    supportsEmbed: true,
    supportsPreview: false,
    allowsRedistribution: true,
    transcriptionSource: true,
    requiresKey: false,
    implemented: false,
    notes: "Bibliothèque nationale de France : à activer avec l'API IIIF + une route de lecture dédiée.",
  },
];

export const connectorKeyValidator = v.string();

export function connectorByKey(key: string): Connector | undefined {
  return CONNECTORS.find((c) => c.key === key);
}

/** Un connecteur est vraiment utilisable s'il est branché ET configuré. */
export function connectorReady(c: Connector): boolean {
  return c.implemented && envReady(c.requiresEnv);
}

/** Liste publique des connecteurs + leur état réel. */
export const list = query({
  args: {},
  handler: async () => {
    // Vérification d'honnêteté : le drapeau `implemented` doit correspondre
    // aux connecteurs réellement présents dans `connectors/`.
    const implemented = new Set(specKeys());
    const mismatched = CONNECTORS.filter((c) => c.implemented !== implemented.has(c.key)).map((c) => c.key);

    return {
      connectors: CONNECTORS.map((c) => ({
        ...c,
        missingEnv: c.requiresEnv.filter((name) => !hasEnv(name)),
        ready: connectorReady(c),
        mode:
          c.implemented && connectorReady(c)
            ? c.searchEnabled
              ? "recherche + rayons"
              : "flux (URL) uniquement"
            : c.implemented
              ? "clé manquante"
              : "registre (non branché)",
      })),
      searchEnabled: CONNECTORS.filter((c) => c.searchEnabled && connectorReady(c)).map((c) => c.key),
      /** Signalé tel quel dans l'admin : un drapeau qui dérive est un bug. */
      mismatched,
    };
  },
});

/** Miroir en base : alimente le dashboard admin et le journal d'erreurs. */
export const sync = internalMutation({
  args: { results: v.optional(v.array(v.object({ source: v.string(), error: v.string() }))) },
  handler: async (ctx, args) => {
    const now = Date.now();
    const errors = new Map((args.results ?? []).map((r) => [r.source, r.error]));
    for (const c of CONNECTORS) {
      const existing = await ctx.db
        .query("ovSources")
        .withIndex("by_key", (q) => q.eq("key", c.key))
        .unique();
      const patch = {
        key: c.key,
        name: c.name,
        kind: c.kind,
        category: c.category,
        homepage: c.homepage,
        docsUrl: c.docsUrl,
        license: c.license,
        requiresEnv: c.requiresEnv,
        searchEnabled: c.searchEnabled,
        streamingAllowed: c.allowsRedistribution,
        notes: c.notes,
        active: connectorReady(c),
        lastError: errors.get(c.key),
        lastCheckedAt: now,
      };
      if (existing) await ctx.db.patch(existing._id, patch);
      else await ctx.db.insert("ovSources", patch);
    }
    return { synced: CONNECTORS.length };
  },
});

export { contactHeaders, envValue, hasEnv };
